magephp:
    #log_dir: /path/to/my/logs
    environments:
        sendbox:
            tar_create: cfh
            tar_create_path: tar
            tar_extract: xf
            tar_extract_path: tar
            user: zhenpeng8
#            branch: master
            from: /data0/task
            host_path: /var/www/tmp
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - 127.0.0.1
            pre-deploy:
                - deploy/tar/prepare
#                - git/update
#                - composer/install
#                - composer/dump-autoload
            on-deploy:
                - deploy/release/prepare
                - deploy/tar/copy
            on-release:
                - deploy/release
            post-release:
                - deploy/release/cleanup
            post-deploy:
                - deploy/tar/cleanup
